### ISSUE TITLE
ReSharper Cleanup Code and StyleCop plugin

### ISSUE THREAD

**Issue by Pat781** [kubiix/ReSharper.StyleCop#16]
Hello,

after installing the StyleCop plugin 4.7.60 Alpha 2, I'm not able anymore to use the ReSharper feature of Cleanup Code (ReSharper->Tools->Cleanup Code...). This is again available after uninstalling the StyleCop plugin.

Regards,
Patrick

**Comment by wilhen01** [comment]
@Pat781 I think this plugin has been abandoned, there's a new one available here: https://resharper-plugins.jetbrains.com/packages/StyleCop.StyleCop/

**Comment by Uladzimir-Kavaliuk** [comment]
@wilhen01 Context menu commands like "Run StyleCop" don't work with StyleCop by JetBrains.

**Comment by Pat781** [comment]
Thanks, the new plugin works
